### ISSUE TITLE
Wrong X server used

### ISSUE THREAD

**Issue by porst17** [Robobench/tacklebox#6]
It looks like tacklebox is hard-coded to use the `unix:0.0` X11 socket, but on my machine, `DISPLAY` is set to `1.0` since I have two GPUs (Intel + NVidia) which are connected via NVidia Optimus (the Intel GPU is connected to the display and the NVidia GPU is rendering into some buffer which is displayed by the Intel GPU AFAIK). This is the default setting when using NVidia Prime or the bumblebee project to make use of both cards somehow.

I adjusted `host_x_component.py` to use `unix:1.0` instead and `tackle component-demo` shows `glxgears` as expected. Maybe you can make use of the `DISPLAY` variable of the host instead of hard-coding the X11 socket.

**Comment by jon-weisz** [comment]
@porst17 When you get a chance, could you verify this works for you?

Issue #7 will make this problem easier to handle in the future, but for now I didn't try to solve the problem of what  to do if you don't have a DISPLAY variable set and the default one doesn't point at a valid X server.

**Comment by porst17** [comment]
Tested. Works.
